### ISSUE TITLE
key repeat on Mac OS

### ISSUE THREAD

**Issue by shivahnshankar** [johtela/vscode-modaledit#20]
Hi,
with the vim config, pressing a key for a long time does not activate repeat commands. For ex: holding j does not scroll the cursor down.
Is there any configuration that can allow this?
Thanks

**Comment by johtela** [comment]
Hi,

Apparently other Vim plugins have the same problem, and have found a workaround. You could try [this setting](https://wesleywiser.github.io/post/vscode-vim-repeat-osx/)

**Comment by haberdashPI** [comment]
Yeah, just to chime in here (happened to see this issue); this isn't a limitation of `vscode-modaledit` per se, but a limitation of VSCode on MacOS. Try holding down e.g. "j" for a long time without modaledit installed; the last time I tried this I got a menu with various types of accents I could add to "j" (rather than repeating j).

**Comment by shivahnshankar** [comment]
Thanks that fixed the issue.
